import type { ScriptPattern } from "../types.js";

export const analyticsPatterns: ScriptPattern[] = [
  {
    id: "google-analytics-ua",
    name: "Google Analytics (Universal)",
    vendor: "Google",
    category: "analytics",
    urlPatterns: [
      "*://www.google-analytics.com/analytics.js",
      "*://www.google-analytics.com/ga.js",
    ],
    globalVariables: ["ga", "GoogleAnalyticsObject"],
    knownIssues: [
      "Legacy version - migrate to GA4",
      "Sets multiple cookies",
      "Sends data to Google servers",
    ],
    alternatives: ["Plausible", "Fathom", "Simple Analytics"],
    docsUrl: "https://developers.google.com/analytics/devguides/collection/analyticsjs",
  },
  {
    id: "google-analytics-4",
    name: "Google Analytics 4",
    vendor: "Google",
    category: "analytics",
    urlPatterns: [
      "*://www.googletagmanager.com/gtag/js*",
      "*://www.google-analytics.com/g/collect*",
    ],
    globalVariables: ["gtag", "dataLayer"],
    knownIssues: [
      "Sets multiple cookies",
      "Sends data to Google servers",
      "May require cookie consent banner",
    ],
    alternatives: ["Plausible", "Fathom", "Simple Analytics"],
    docsUrl: "https://developers.google.com/analytics/devguides/collection/ga4",
  },
  {
    id: "segment",
    name: "Segment",
    vendor: "Twilio",
    category: "analytics",
    urlPatterns: [
      "*://cdn.segment.com/analytics.js/*",
      "*://cdn.segment.io/analytics.js/*",
      "*://api.segment.io/*",
    ],
    globalVariables: ["analytics"],
    knownIssues: [
      "Can load many downstream integrations",
      "May increase page weight significantly",
    ],
    alternatives: ["RudderStack", "Jitsu"],
    docsUrl: "https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    vendor: "Mixpanel",
    category: "analytics",
    urlPatterns: [
      "*://cdn.mxpnl.com/*",
      "*://api.mixpanel.com/*",
      "*://cdn.mixpanel.com/*",
    ],
    globalVariables: ["mixpanel"],
    knownIssues: ["Tracks user behavior by default"],
    alternatives: ["PostHog", "Amplitude"],
    docsUrl: "https://developer.mixpanel.com/docs/javascript",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    vendor: "Amplitude",
    category: "analytics",
    urlPatterns: [
      "*://cdn.amplitude.com/*",
      "*://api.amplitude.com/*",
      "*://api2.amplitude.com/*",
    ],
    globalVariables: ["amplitude"],
    knownIssues: ["Tracks user sessions automatically"],
    alternatives: ["PostHog", "Mixpanel"],
    docsUrl: "https://www.docs.developers.amplitude.com/data/sdks/browser-2/",
  },
  {
    id: "heap",
    name: "Heap",
    vendor: "Heap",
    category: "analytics",
    urlPatterns: [
      "*://cdn.heapanalytics.com/*",
      "*://heapanalytics.com/*",
    ],
    globalVariables: ["heap"],
    knownIssues: [
      "Auto-captures all user interactions",
      "Can capture sensitive form data if not configured",
    ],
    alternatives: ["PostHog", "FullStory"],
    docsUrl: "https://developers.heap.io/docs/web",
  },
  {
    id: "plausible",
    name: "Plausible",
    vendor: "Plausible",
    category: "analytics",
    urlPatterns: [
      "*://plausible.io/js/*",
      "*://*.plausible.io/js/*",
    ],
    globalVariables: ["plausible"],
    knownIssues: [],
    alternatives: [],
    docsUrl: "https://plausible.io/docs",
  },
  {
    id: "fathom",
    name: "Fathom",
    vendor: "Fathom",
    category: "analytics",
    urlPatterns: [
      "*://cdn.usefathom.com/*",
      "*://*.usefathom.com/script.js",
    ],
    globalVariables: ["fathom"],
    knownIssues: [],
    alternatives: [],
    docsUrl: "https://usefathom.com/docs",
  },
  {
    id: "posthog",
    name: "PostHog",
    vendor: "PostHog",
    category: "analytics",
    urlPatterns: [
      "*://app.posthog.com/static/*",
      "*://us.posthog.com/static/*",
      "*://eu.posthog.com/static/*",
    ],
    globalVariables: ["posthog"],
    knownIssues: ["Session recording may capture sensitive data"],
    alternatives: [],
    docsUrl: "https://posthog.com/docs/libraries/js",
  },
  {
    id: "hotjar",
    name: "Hotjar",
    vendor: "Hotjar",
    category: "analytics",
    urlPatterns: [
      "*://static.hotjar.com/*",
      "*://script.hotjar.com/*",
    ],
    globalVariables: ["hj", "hjSiteSettings"],
    knownIssues: [
      "Session recording may capture sensitive data",
      "Significant performance impact",
    ],
    alternatives: ["PostHog", "FullStory", "Microsoft Clarity"],
    docsUrl: "https://help.hotjar.com/hc/en-us/articles/115009336727",
  },
  {
    id: "fullstory",
    name: "FullStory",
    vendor: "FullStory",
    category: "analytics",
    urlPatterns: [
      "*://fullstory.com/s/fs.js",
      "*://edge.fullstory.com/*",
      "*://rs.fullstory.com/*",
    ],
    globalVariables: ["FS"],
    knownIssues: ["Session recording may capture sensitive data"],
    alternatives: ["PostHog", "Hotjar"],
    docsUrl: "https://developer.fullstory.com/browser/getting-started/",
  },
  {
    id: "clarity",
    name: "Microsoft Clarity",
    vendor: "Microsoft",
    category: "analytics",
    urlPatterns: [
      "*://www.clarity.ms/*",
    ],
    globalVariables: ["clarity"],
    knownIssues: ["Session recording may capture sensitive data"],
    alternatives: ["PostHog", "Hotjar"],
    docsUrl: "https://learn.microsoft.com/en-us/clarity/",
  },
];
